### ISSUE TITLE
Emulate L0GlobalTIS

### ISSUE THREAD

**Issue by yipengsun** [umd-lhcb/TrackerOnlyEmu#2]
According to the RD+'s arxiv article: 

> The approach here is to directly take this from data, rather than to emulate the full simulation

@Svende could you document what you learned from L0GlobalTIS emulation in this issue?

**Comment by yipengsun** [comment]
I took another look at RD+'s _Figure 13_, and I think there's something fishy about their Y axis: The efficiency is greater than 1!
![rdp_fig_problem](https://user-images.githubusercontent.com/33738176/142785770-d234b772-572c-4b7d-a21b-548d1addc703.png)

Edit: I think these must be effieiency/bin width. But they should really mark it in this case.

**Comment by yipengsun** [comment]
Finally reproduced the Figure 13. Note that the RD+'s Figure 13 uses a MC `B -> J/psi K` efficiency but we don't have the _MC_ efficiency. So I just plotted our MC normalization and signal.

![l0_global_tis_eff_bin_idx](https://user-images.githubusercontent.com/33738176/142965001-7a5742c9-7ad6-49d1-871c-9c160b2dab03.png)
![l0_global_tis_eff_log_pt](https://user-images.githubusercontent.com/33738176/142965005-1eb38c23-1cce-4e6f-a004-6790fcec8829.png)
![l0_global_tis_eff_log_pz](https://user-images.githubusercontent.com/33738176/142965006-f0d90ef5-2a26-441f-84b8-44443f70d839.png)

**Comment by yipengsun** [comment]
I checked my code and don't think the `log(PT)` is implemented incorrectly. I need to think more on why the efficiencies look like this.

**Comment by yipengsun** [comment]
Previously the normalization and signal was swapped. I've fixed that and add the efficiencies with the direct `TIS/num of event` division

## TISTOS method
![l0_global_tis_eff_bin_idx](https://user-images.githubusercontent.com/33738176/143662922-66a7eed6-5619-49ca-b63a-6d2de9e5934f.png)
![l0_global_tis_eff_log_pt](https://user-images.githubusercontent.com/33738176/143662923-4f1c09c8-7b40-4d4c-ad30-dd64a85b3ef6.png)
![l0_global_tis_eff_log_pz](https://user-images.githubusercontent.com/33738176/143662924-91b3576f-43d9-4623-9270-cae7c6f4199b.png)

## Direct method
![l0_global_tis_eff_bin_idx_dir](https://user-images.githubusercontent.com/33738176/143662929-f6d0797a-b345-4219-aab0-bb7de455665c.png)
![l0_global_tis_eff_log_pt_dir](https://user-images.githubusercontent.com/33738176/143662932-8f3999e6-f2bd-484e-9915-fb8b7e28c9d4.png)
![l0_global_tis_eff_log_pz_dir](https://user-images.githubusercontent.com/33738176/143662933-98a226de-ab3e-4c09-9b50-18df4fd51081.png)

**Comment by yipengsun** [comment]
I still don't have a feeling about the shape of the efficiencies. We naively expect the efficiency to be monotonously increasing for L0Global TIS, but I don't have too much to explain other than "higher PT in `B` means the daughters have a higher chance to NOT captured by the detector".

Also, I checked the efficiencies in `J/psi K` real data, and it is NOT monotonous in `log(PZ)`!:
![data_log_pt](https://user-images.githubusercontent.com/33738176/143663061-eac983d5-28fa-4d76-8925-a2e07153425c.png)
![data_log_pz](https://user-images.githubusercontent.com/33738176/143663062-fa0afc12-79ba-4f90-a10c-cc807ea320c0.png)

**Comment by yipengsun** [comment]
TISTOS doesn't agree w/ TIS not TOS:

![l0_global_tis_eff_bin_idx_comp](https://user-images.githubusercontent.com/33738176/144451479-6b5f701f-4085-48c6-8d4a-119476574416.png)
![l0_global_tis_eff_log_pt_comp](https://user-images.githubusercontent.com/33738176/144451482-174edee2-34ed-4893-86a7-26fac28847c0.png)
![l0_global_tis_eff_log_pz_comp](https://user-images.githubusercontent.com/33738176/144451483-77bacd50-c06c-4659-bdad-9e70f646bcae.png)

**Comment by yipengsun** [comment]
I applied a global `nSPDhits < 450` cut, and there's not much difference:
![l0_global_tis_eff_bin_idx_comp](https://user-images.githubusercontent.com/33738176/144664595-9609c49a-ee43-4a72-80eb-9e9099f1b273.png)
![l0_global_tis_eff_log_pt_comp](https://user-images.githubusercontent.com/33738176/144664598-4f39cbb0-2873-4b6a-b041-2f055ad6d1bb.png)
![l0_global_tis_eff_log_pz_comp](https://user-images.githubusercontent.com/33738176/144664601-fda369cb-c2d7-47a2-a22b-67f6943035d2.png)

**Comment by yipengsun** [comment]
@manuelfs @Svende @afernez Here's a draft to RD+:

We are trying to recreate _Fig. 13_ in your trigger emulation note:
![rdp_fig_problem](https://user-images.githubusercontent.com/33738176/142785770-d234b772-572c-4b7d-a21b-548d1addc703.png)

We believe that you've shown TISTOS method _at least_ can be applied to the `J/psi K` mode in _Fig. 12_, so we just need to show for our _normalization_ and _signal_ MC, they have compatible `L0 Global TIS` efficiency.

Initially we used _TISTOS method_ to find efficiencies for _normalization and _signal_, but they disagree by quite a margin; then we tried to use the _direct method_ (number of TIS / number of events per bin) and they have better agreement. For more details, see https://github.com/umd-lhcb/TrackerOnlyEmu/issues/2#issuecomment-980477731

Note that for TISTOS method, we used `L0 Hadron TOS` as the TOS.

In your _Fig. 13_, which method did you use to evaluate the trigger efficiency (TISTOS or direct)?

**Comment by yipengsun** [comment]
With `L0Muon TOS` as the TISTOS TOS trigger, the efficiencies are in better agreement:
![l0_global_tis_eff_bin_idx_comp](https://user-images.githubusercontent.com/33738176/145210304-b4153fc8-6d1d-475c-8e50-0552bbf1db9d.png)
![l0_global_tis_eff_log_pt_comp](https://user-images.githubusercontent.com/33738176/145210306-d6889a1e-94ef-4ec0-8591-a777c79d829e.png)
![l0_global_tis_eff_log_pz_comp](https://user-images.githubusercontent.com/33738176/145210309-bd2bfb9c-fd9a-4435-879f-35f99d59f19b.png)

**Comment by yipengsun** [comment]
Useful TISTOS info that I'll organize into a doc: https://indico.cern.ch/event/603961/contributions/2532418/attachments/1440328/2217123/L0TISTOS.pdf

**Comment by yipengsun** [comment]
Quick summary: Using **true** B kinematics makes the efficiencies between sig. and norm. agree. Still digesting Phoebe's info on TISTOS.

![l0_global_tis_eff_log_pt_dir](https://user-images.githubusercontent.com/33738176/145474142-98709ca0-b854-4ef1-b632-3163aa9c4f52.png)
![l0_global_tis_eff_log_pz_dir](https://user-images.githubusercontent.com/33738176/145474143-89206ad1-413d-49ef-849a-2c7fc6bcba57.png)
![l0_global_tis_eff_bin_idx_dir](https://user-images.githubusercontent.com/33738176/145474091-16596c10-5220-4c12-b417-a3d3341f11dc.png)

**Comment by Svende** [comment]
Could you do the same plots as above using the TISTOS method? Just to see if they are still different.

**Comment by yipengsun** [comment]
I think in [this comment](https://github.com/umd-lhcb/TrackerOnlyEmu/issues/2#issuecomment-988779297) the TISTOS vs TIS not TOS already showed good agreement, which shows that by using the correct L0 TOS trigger, the efficiencies are already pretty consistent.

**Comment by Svende** [comment]
Right but the above plots were with the reconstructed quantities, so to close the loop I think it make sense to have all of the plots as in the end the TISTOS eff. in data for JpsiK will be used as a weight in simulation. Please also see my related comment here: https://github.com/umd-lhcb/rdx-run2-analysis/issues/44
